# Generated by Django 5.0.7 on 2024-07-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='list_items',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='quiz_data',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('header', 'Header'), ('paragraph', 'Paragraph'), ('list', 'List'), ('code', 'Code')], max_length=10)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('list_items', models.TextField(blank=True, null=True)),
                ('code_content', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
