# Generated by Django 5.0.7 on 2024-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_slug_lesson_slug_unit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='quiz_data',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_url',
        ),
        migrations.AddField(
            model_name='content',
            name='list_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('header', 'Header'), ('paragraph', 'Paragraph'), ('list', 'List')], max_length=10),
        ),
    ]
