# Generated by Django 5.0.7 on 2024-07-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_content_type_remove_lesson_list_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('header', 'Header'), ('paragraph', 'Paragraph'), ('list', 'List'), ('code', 'Code'), ('video', 'Video')], max_length=10),
        ),
    ]
