# Generated by Django 5.0.7 on 2024-07-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='quiz_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
